### ISSUE TITLE
Strange texture appearing every time I press K

### ISSUE THREAD

**Issue by Punkgrin** [DominicKarma/WrathOfTheGodsPublic#1]
Today I loaded up tmodloader and noticed there was a new patch. I didn't think much of it, but about a minute later when I had loaded in, I noticed every time I press K on my keyboard it makes this strange texture show up on screen, reminiscent of an RGB keyboard, except green and red. 
![weirdkeyboardthing](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/147355612/88c80275-d4e9-4e6d-9259-f1cdf4b3b648)
If you're wondering why I would even use K as a bind, it's because I play left-handed due to carpal tunnel in my right wrist, so it's the bind I use to go left. Regardless, I have confirmed it's specifically the mod that causes it, as after disabling it, there was no texture. It's also confirmed to be K and only K, since I changed my left bind and it still showed up. To be honest, this is only a minor inconvenience, but it would still be much appreciated if it could be fixed (even though this is probably only affecting like 3 people). Cheers very much!
(also I have no idea how useful the log files would be in this scenario, but here they are anyway)
[logs.zip](https://github.com/DominicKarma/WrathOfTheGodsPublic/files/14227640/logs.zip)

**Comment by DominicKarma** [comment]
Ah, crap. I forgot to switch to release mode and compiling the mod. One second, I'll make a new release with this removed.
Thank you for letting me know.

**Comment by Punkgrin** [comment]
I AM ASTOUNDED at how fast that was. Honestly legendary developer. I dunno how much you get that, but you've certainly made something quite special to the tmod community. Keep it up mate.
