### ISSUE TITLE
Noxus kills nameless deity

### ISSUE THREAD

**Issue by Catdot1** [DominicKarma/WrathOfTheGodsPublic#10]
When you go to the Eternal Garden after the nameless deity spawns you can spawn noxus and they fight eachother while fully ignoring the player. me and my friend found this while playing multiplayer and also tried it on slingleplayer and it worked.
You can cheese nameless deity like that and just stay in one place not moving cuz noxus kills nameless deity and after nameless dies noxus gets killed by the death stage from nameless deity
![noxus vs namelesss](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/162806308/5fda4ac0-7062-474f-b6c1-34faa5543fc8)
![image noxus vs nameless](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/162806308/fe028c87-cb30-4136-a9e2-f566d8083818)

**Comment by DominicKarma** [comment]
This, while being unorthodox, is technically not bugged behavior. That interaction between the two bosses is explicitly programmed. It's obscure and amusing enough that I personally don't believe its use as a cheese strat warrants removal.

**Comment by Catdot1** [comment]
> This, while being unorthodox, is technically not bugged behavior. That interaction between the two bosses is explicitly programmed. It's obscure and amusing enough that I personally don't believe its use as a cheese strat warrants removal.

im not saying it should be removed i just thought it was unknown and wanted to let ppl and you know
