### ISSUE TITLE
game freezing after entering subworld

### ISSUE THREAD

**Issue by hellobot2001** [DominicKarma/WrathOfTheGodsPublic#12]
I've been trying to enter the subworld, and I have succeeded every time. the problem is that the game freezes shortly after I do, so I am unable to do anything unless I restart.

https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/79287930/656f214f-6be4-461d-bd66-00ef3a6b10de

[client.log](https://github.com/DominicKarma/WrathOfTheGodsPublic/files/14625815/client.log)

**Comment by DominicKarma** [comment]
The logs indicate an error in player update logic pertaining to a mod known as "MoreAccessories". Does disabling it address the issue?

**Comment by hellobot2001** [comment]
no, I disabled it and it still freezes.

**Comment by hellobot2001** [comment]
after some testing I found that the problem came from a mod called "dragon ball terraria."

**Comment by LightMakerStudios** [comment]
Can a fix be made please?
