### ISSUE TITLE
Nameless Deity Immediately dying upon spawn

### ISSUE THREAD

**Issue by Void866** [DominicKarma/WrathOfTheGodsPublic#16]
So as of recently (before updates on the 23rd), Upon heading to Deity's world and then standing under the tree to spawn him in, he does his spawn animation as per normal. However a repetitive (I have no idea how to describe this) thumping sound plays constantly over and over, it sounds like one of his attack sound effects but honestly im not sure.

 When the boss fight actually starts, he's already on 1 HP, and so enters his final attack before the fight immediately ends. This happens every time he spawns, regardless of the character or world used. 
 
 The mod list im using is the same as my previous Issue I posted (https://github.com/DominicKarma/WrathOfTheGodsPublic/issues/9). I've check both Client.log and Server.log (Although this is happening in singleplayer, but just incase) and it only shows the mods loading correctly. It doesn't show anything occurring during the game. (Unless im missing a file that does), let me know if you want some screen shots of the files anyway.

**Comment by DominicKarma** [comment]
Hmm. That's really strange. I'll see if I can get this to happen for myself. The boss fight starting at 1 HP is especially concerning.

**Comment by Void866** [comment]
Im trying to get some footage for you. Give me a moment

**Comment by Void866** [comment]
[https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/c0565128-3f30-4233-94c3-c7f0d6dc1243](url)

This is on a fresh new world (I quickly used cheat sheet to unlock the terminus), on a fresh character. I've tried disabling all the major content mods (I haven't checked the smaller mods yet) that i'd have thought might be causing this and it still occurs.

**Comment by Void866** [comment]
Hey, ive recently returned to the mod after a bunch of updates have passed. The issue was still present. However i've found the issue that's causing it. To my surprise it was actually the "Cheat sheet" mod that was causing the issue (and the one I thought would have the lowest chance of causing it). I believe it has something to do with nameless being disabled in the mods boss spawn list (not sure how). 

Not sure if this is something you can fix as well there's still nothing present in the server.log and client.log or if its more of an issue with the cheat sheet mod than your mod. I will do a fresh reinstall of the cheat sheet mod however, the issue has been "fixed" so I'll close this thread after I double check with the fresh reinstall. Thanks for your help @DominicKarma

**Comment by Void866** [comment]
Can confirm cheat sheet is the issue, just reinstalled and the boss still breaks. I'll close this thread now.
