### ISSUE TITLE
A minor incompatibility between mods

### ISSUE THREAD

**Issue by starnmoons** [DominicKarma/WrathOfTheGodsPublic#21]
I think for some reason there's an issue where if you have calamity vanities addon, nameless deity seems to drop termipebbles (calamity vanities item) instead of good apples

**Comment by DominicKarma** [comment]
I'm not sure I follow? I know CalVal makes the Xerocodiles (which drop that item) appear in the Garden, but the apples fallen from the tree should still grant the equivalent item upon being touched. I can say with certainty at least that WoTG doesn't do anything with respect to either of those pieces of content.
