### ISSUE TITLE
vision of garden crash

### ISSUE THREAD

**Issue by Dirt65** [DominicKarma/WrathOfTheGodsPublic#23]
well, when i have the vision of garden when i reach to up it crashes when scene end
![20240404210912_1](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/75103434/8f5fd29f-69e8-4640-b805-92ca5e495a04)
![222](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/75103434/caa3bf28-9b9b-41d5-ba01-be6ecc1e2431)

**Comment by DominicKarma** [comment]
Have received reports of this from extraneous sources. I'll leave this issue up until the next patch addresses it, though.
