### ISSUE TITLE
Question regarding fan-made compositions and other works.

### ISSUE THREAD

**Issue by JalventScientist** [DominicKarma/WrathOfTheGodsPublic#26]
Recently checked out the mod and thought it was fantastic. I've been wanting to make like a sort of fan-song for the Nameless deity but so far i've seen  nothing mentioned regarding forms of credit or copyright when publishing.

So, what's up with that? Is just mentioning the team in the credits good enough, or does it require more forms of approval?

**Comment by DominicKarma** [comment]
Just credit in the description or whatever should be fine?
