### ISSUE TITLE
nameless deity fight not working

### ISSUE THREAD

**Issue by morefour101** [DominicKarma/WrathOfTheGodsPublic#30]
when you spawn nameless detiy, oddly you can move around when normally you couldn't, I do not know if this is a bug but onto the main part, after he spawns your entire game freezes then it crashes

**Comment by DominicKarma** [comment]
Log file have anything interesting?

**Comment by Kenatooooooo** [comment]
I think I know where the issue comes from: the blackhole attack. The game always crashes during this attack, or right when it finishes. I don't know if that's the case for everyone, though.

**Comment by MRKARTOFAN** [comment]
Going to join conversation. For some reason, the game freezing at the beginning of the fight with Nameless Deity, the freezing fixes when i resetting settings to default (but there were on default, but somehow resetting fixes that?).
I tried to start a fight without any additional mods, just calamity and wrath of gods - issue persist.
Here is the crashlog

> System.Exception: Fatal Deadlock in FastParallelFor. pending: 0. avail: 32766
>    at ReLogic.Threading.FastParallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelForAction callback, Object context) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Threading\FastParallel.cs:line 102
>    at Luminance.Core.Graphics.ParticleManager.PostUpdateDusts() in Luminance\Core\Graphics\Particles\ParticleManager.cs:line 46
>    at Terraria.ModLoader.SystemLoader.PostUpdateDusts() in tModLoader\Terraria\ModLoader\SystemLoader.cs:line 319
>    at DMD<System.Void Terraria.Main:DoUpdateInWorld(System.Diagnostics.Stopwatch)>(Main this, Stopwatch sw)
>    at SyncProxy<System.Void Terraria.Main:DoUpdateInWorld(System.Diagnostics.Stopwatch)>(Main , Stopwatch )
>    at DMD<System.Void Terraria.Main:DoUpdate(Microsoft.Xna.Framework.GameTime&)>(Main this, GameTime& gameTime)
>    at HighFPSSupport.TickRateModifier.OnDoUpdate(orig_DoUpdate orig, Main self, GameTime& gameTime) in HighFPSSupport\TickRateModifier.cs:line 138
>    at Hook<System.Void HighFPSSupport.TickRateModifier::OnDoUpdate(Terraria.On_Main+orig_DoUpdate,Terraria.Main,Microsoft.Xna.Framework.GameTime&)>(Main , GameTime& )
>    at SyncProxy<System.Void Terraria.Main:DoUpdate(Microsoft.Xna.Framework.GameTime&)>(Main , GameTime& )
>    at DMD<System.Void Terraria.Main:Update(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
>    at Hook<System.Void BTitles.BiomeTitlesMod::Update(Terraria.On_Main+orig_Update,Terraria.Main,Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
>    at SyncProxy<System.Void Terraria.Main:Update(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
>    at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 488
>    at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
>    at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
>    at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266
>    at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 240
>    at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 213
>    at Terraria.MonoLaunch.Main_End(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 78
>    at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1() in tModLoader\Terraria\MonoLaunch.cs:line 64
>    at System.Threading.Thread.StartCallback()
Here is the full log 
[client.log](https://github.com/DominicKarma/WrathOfTheGodsPublic/files/15066790/client.log)
Video demonstration of situation: https://www.youtube.com/watch?v=pah1zOe5cis

**Comment by MRKARTOFAN** [comment]
Follow up: waiting some time and it's unfreezes itself.
