### ISSUE TITLE
JIT exceptions in most recent update

### ISSUE THREAD

**Issue by Snailetiquette** [DominicKarma/WrathOfTheGodsPublic#34]
As title says. Please see image below.
![image](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/98176984/1ddcb7ed-22f4-483a-b8d0-9e9fe4ba1505)

**Comment by DominicKarma** [comment]
Is Luminance in version 1.0.3?

**Comment by Snailetiquette** [comment]
Just checked, I was on 1.0.2. Just updated and it works now, thanks!
