### ISSUE TITLE
 version 1.1.23 of the mod cannot launch

### ISSUE THREAD

**Issue by zhouy25** [DominicKarma/WrathOfTheGodsPublic#36]
![image](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/168671144/48fce388-3caa-44a8-8497-bc5a9d97bbff)

**Comment by DominicKarma** [comment]
Is Luminance at version 1.0.3?

**Comment by zhouy25** [comment]
Oh, I see. Thank you for your helping. Have a nice day :)
