### ISSUE TITLE
Instant crash after the stairs cutscene leading up to the nameless deity.

### ISSUE THREAD

**Issue by zygis23** [DominicKarma/WrathOfTheGodsPublic#37]
After the climb and the cutscene that is supposed to be a lead-up to the upcoming boss fight of nameless deity the game fully crashes as the screen turns white. Giving this crash message: 

![Screenshot_1](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/77207394/5339d38d-c26d-40a8-bfc5-82b924022c23)
Log:
[client.log](https://github.com/DominicKarma/WrathOfTheGodsPublic/files/15179733/client.log)

**Comment by DominicKarma** [comment]
Bleh, this is gonna be a bit unpleasant to untangle. I'll see about getting it out of the way later today and then making a patch. Thank you for bringing this up.

**Comment by DominicKarma** [comment]
There. Latest patch should address this by replacing the insecure, obsolete BinaryFormatter class.

**Comment by zygis23** [comment]
Oh, thank you very much for taking your time. Have a nice day.
