### ISSUE TITLE
Mod fails to load on title screen

### ISSUE THREAD

**Issue by ethanfan1033** [DominicKarma/WrathOfTheGodsPublic#42]
WoTG v1.1.24
tModLoader v2024.3.3.2
Terraria v1.4.4.9

I am unable to load the mod due to an error with not being able to find a function in the code. Here is the log:
[client.log](https://github.com/DominicKarma/WrathOfTheGodsPublic/files/15214900/client.log)

Current mod list:
[
  "SerousCommonLib",
  "UnCalamityModMusic",
  "CalamityMod",
  "SubworldLibrary",
  "MagicStorage",
  "RecipeBrowser",
  "CalamityModMusic",
  "CheatSheet",
  "BossChecklist",
  "Luminance",
  "NoxusBoss",
  "InfernumMode"
]

**Comment by DominicKarma** [comment]
It's because your Luminance version is out of date. The latest version is 1.0.3.
