### ISSUE TITLE
Requires Luminance and Subworld Library

### ISSUE THREAD

**Issue by willuwontu** [DominicKarma/WrathOfTheGodsPublic#60]
The workshop page for the mod fails to mention that it requires these 2 mods or list them as required items for it.

The [README.md](https://github.com/DominicKarma/WrathOfTheGodsPublic/blob/main/README.md) also fails to mention that they are required for it as well.

**Comment by DominicKarma** [comment]
Surprised that isn't something that's done automatically by steam. I've listed those two on there.
