### ISSUE TITLE
Nameless Deity not giving off any loot and not being checked off in boss checklist.

### ISSUE THREAD

**Issue by TERSATERR** [DominicKarma/WrathOfTheGodsPublic#7]
I have NO idea what caused this to happen, I would also like to mention the first time I killed him, game crashed but I got the "You Passed The Test" menu, but with no items. Then I tried again and the game DIDN'T crash on me, but still I didn't get anything from Nameless Deity and he wasn't checked off in boss checklist.
Heres some Video Proof:
https://youtu.be/CshjbE8NmWI
Here's the logs:
[client.log](https://github.com/DominicKarma/WrathOfTheGodsPublic/files/14354026/client.log)

**Comment by DominicKarma** [comment]
Out of curiosity, do you have your player character data saved on the cloud?

**Comment by TERSATERR** [comment]
> Out of curiosity, do you have your player character data saved on the cloud?

Sorry for the late response, but yes the character data is saved on the cloud.

**Comment by DominicKarma** [comment]
That explains it, then. I'll make a patch addressing in a bit.

**Comment by TERSATERR** [comment]
For curiosity sake, why does that cause the issue?

**Comment by DominicKarma** [comment]
File handle checks in the player-saving (Nameless has to enable a small flag in the player's save data in order for them to know they need to receive loot upon re-entering the world) inevitably failing when there's no actual file on the hard-drive to look at
