### ISSUE TITLE
Game crashing during gameplay issue, only began post-ML defeat.

### ISSUE THREAD

**Issue by Eternal221** [DominicKarma/WrathOfTheGodsPublic#79]
[backupclient.log](https://github.com/user-attachments/files/17451625/backupclient.log)

Log is called 'backupclient' because its an archived variant of the log, which I took before attempting to fix the issue myself to no avail.
The game crashes w/o a clear reason, no error messages are displayed, the game simply freezes for a moment and then closes.
I suspect it has something to do with the autosave, but I cannot tell, as it does not crash every day/night cycle, seemingly only randomly.
Player-data is saved on crash, but world data is not. Results in varied loss of progress.

I apologize if this is not an issue with this mod, I'm checking due to it being the only 'new' mod I have installed recently. Every other mod used has not had this issue previously, and have been used to game completion.

**Comment by DominicKarma** [comment]
This issue does not seem to be related to WoTG. The logs indicate that there's an error being thrown when saving tile entity data (such as weapon racks, target dummies, plates, Calamity's charging stations, etc.). This is definitely the source of the aforementioned world data corruption. But WoTG does not do anything with tile entities, nor does it hook into the world save functionalities.

**Comment by Eternal221** [comment]
Ah thank you. I'll consult some other mods then. Sorry for your time, I can't read crashlogs very well.
I'll note this for later.
