### ISSUE TITLE
Error while loading this mod, detected to be built for other Tmodloader version, Calremix incompatibility

### ISSUE THREAD

**Issue by yoopgim** [DominicKarma/WrathOfTheGodsPublic#84]
crashes at "configuring content" stage:

![Screenshot 2024-12-31 110536](https://github.com/user-attachments/assets/64c8ce01-eafe-4908-9a35-58abd0b7c5ea)

[client.log](https://github.com/user-attachments/files/18282800/client.log)

I conviniently have the mods used in a collection as well: https://steamcommunity.com/sharedfiles/filedetails/?id=3389644829

Removing calremix allowed it to load correctly, though considering its importance in my current playthrough and it's integration with this mod, it is far from ideal. here is the when removing calremix: 
[client.log](https://github.com/user-attachments/files/18282837/client.log)

**Comment by DominicKarma** [comment]
Your WoTG version is out of date. The error says your version is 1.1.28, whereas latest (which addresses the CalRemix problem) is 1.1.30.

**Comment by yoopgim** [comment]
ah
