### ISSUE TITLE
Mod Auto Disabling in Multiplayer?

### ISSUE THREAD

**Issue by Void866** [DominicKarma/WrathOfTheGodsPublic#9]
So I've tested the mod in single player without issue (great job btw) and decided to host in multiplayer to see if everything loads up neatly so I could possibly play with friends. However, when I do, tmodloader reloads the mods and disables this mod, so neither of the 2 bosses are in the game. As stated before, this doesn't occur in single player. 

Has the mod recently been updated to not allow multiplayer for testing or something?
Or is it a possible mod incompatibility, attached are some screenshots of my mod list, in case you think anything may be causing it (Excuse the many screen shots, I mod alot)

If not, then I'm not sure why this is happening. 
I'd just like to know if you think this is a problem with compatibility with mods installed or possibly a bug with the mod. 
Thanks. 

![Capture](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/4ff46c93-df21-45f2-a59d-13ed6b1499ee)
![Capture8](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/cff31bf6-7430-47ec-aeb1-70c1722c96d6)
![Capture2](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/f24e63f6-a10c-4c41-808e-964e217c0bb4)
![Capture3](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/af7c7614-b3a4-4b26-9760-bb8bfbd240d3)
![Capture4](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/e4fa662f-a53e-4252-9636-718d1dc1e418)
![Capture5](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/0b36127b-93f8-46bb-a424-ea386d8516b4)
![Capture6](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/e61d8dd2-adcc-4c28-8bc0-ee8d90fd2fcd)
![Capture7](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/0926047c-f7c6-4b08-af9b-a34891fb7c69)

**Comment by Void866** [comment]
I believe I know what mod is causing a compatibility issue, however it the strange part is it works in singleplayer, but not multiplayer. Attached below is the screenshots of server.log issues I found. 

![yes](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/d1cc433d-c782-43bf-80b5-522cb56c67ce)
![yes2](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/61beed5f-eec4-4f50-bb1f-3727b2a6608b)
![yes3](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/871f151d-ade0-42f1-a9b8-2f8a0a110865)

Strangely in this last screenshot, tmod disabled the mod as it believes the mod is outdated. (Although it clearly isnt since it works in multiplayer) before reporting more problems about the compatibility
![Yes4](https://github.com/DominicKarma/WrathOfTheGodsPublic/assets/108363813/3791bdb2-42b2-408e-84f1-135f81d6176d)

I have no idea if this is an issue with this mod, or the other mod. But I appreciate it if you could take a look. Also let me know if you need the Client.log. Thanks.

**Comment by DominicKarma** [comment]
These logs indicate that it's a problem with the CalamityRemix mod, albeit one that I can address in Wrath of the Gods by merit of the fact that it's cross-compatibility code. I'll mark this down for the next update.
